"""
Django settings for weather_gui project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'h)cxk8+sxm1h9_vd$99*wa7hh^$au+6afp&!v$zb+@=qlm$wwb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', 'localhost', '127.0.0.1', '0.0.0.0']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'application.weather.apps.WeatherConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'weather_gui.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_settings_export.settings_export',
            ],
        },
    },
]

WSGI_APPLICATION = 'weather_gui.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

OPEN_WEATHER_API_URL = "https://api.openweathermap.org/data/2.5/onecall/"
WEATHER_BIT_API_URL = "https://api.weatherbit.io/v2.0/history/daily"
WEATHER_BIT_CURRENT_API_URL = "https://api.weatherbit.io/v2.0/current"
WEATHER_BIT_ICON_URL = "https://www.weatherbit.io/static/img/icons/"
OPEN_WEATHER_API_KEY = "a436543830269916008d2e07cfa7f8db"
WEATHER_BIT_API_KEY = "33d1458b97ef4e8cb046adcc056f2861"
WEATHER_BIT_USER_EMAIL = "tocay20113@emailhost99.com"
USER_EMAIL = "abhijeet.anand99@gmail.com"
API_TOKEN = "8M9Q2jN6IdamTxsRqDxSar-DKrEuuG4YCMVU0o2SW8KtcDOZbqEyn3daizZ-_6q81n8"
GET_ACCESS_TOKEN = "https://www.universal-tutorial.com/api/getaccesstoken"
COUNTRY_API = "https://www.universal-tutorial.com/api/countries/"
STATE_API = "https://www.universal-tutorial.com/api/states/"
CITY_API = "https://www.universal-tutorial.com/api/cities/"
LAT_LONG_API = "https://geocode.xyz/"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

SETTINGS_EXPORT = [
    'STATE_API',
    'CITY_API',
    'LAT_LONG_API',
    'WEATHER_BIT_API_URL',
    'WEATHER_BIT_API_KEY',
    'WEATHER_BIT_CURRENT_API_URL',
    'WEATHER_BIT_ICON_URL',
]

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
